--- @alias SearchEngine
--- | "google"
--- | "bing"
--- | "duckduckgo"
--- | "ecosia"
--- | "brave"
--- | "perplexity"
--- | string

--- @class Config
--- @field engine SearchEngine The search engine to use (default: "google")
--- @field command_search string The command for search (default: "WitSearch")
--- @field command_search_visual string The command for visual search (default: "WitSearchVisual")
--- @field command_search_wiki string The command for wiki search (default: "WitSearchWiki")
